/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pagina_Principal;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import plantilla_1.Panel_tomaDatos;

/**
 *
 * @author m3l4n
 */


public class Panel_Principal extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Principal
     */
    JFrame contenedorPrincipal;
    public Panel_Principal(JFrame contenedorPadre) {
        contenedorPrincipal = contenedorPadre;
        
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucido2 = new org.edisoncor.gui.panel.PanelTranslucido();
        buttonTransluceIcon2 = new org.edisoncor.gui.button.ButtonTransluceIcon();
        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        jLabel2 = new javax.swing.JLabel();
        buttonAqua2 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua3 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua4 = new org.edisoncor.gui.button.ButtonAqua();
        buttonTransluceIcon1 = new org.edisoncor.gui.button.ButtonTransluceIcon();

        setPreferredSize(new java.awt.Dimension(800, 567));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTranslucido2.setBackground(new java.awt.Color(51, 0, 102));
        panelTranslucido2.setColorPrimario(new java.awt.Color(51, 204, 255));
        panelTranslucido2.setColorSecundario(new java.awt.Color(51, 51, 255));

        buttonTransluceIcon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\m3l4n\\OneDrive\\Documentos\\NetBeansProjects\\PLANEA\\Images\\exit2.png")); // NOI18N
        buttonTransluceIcon2.setText("buttonTransluceIcon1");
        buttonTransluceIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransluceIcon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucido2Layout = new javax.swing.GroupLayout(panelTranslucido2);
        panelTranslucido2.setLayout(panelTranslucido2Layout);
        panelTranslucido2Layout.setHorizontalGroup(
            panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucido2Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(buttonTransluceIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTranslucido2Layout.setVerticalGroup(
            panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTransluceIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
        );

        add(panelTranslucido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 540));

        panelTranslucido1.setBackground(new java.awt.Color(51, 0, 102));
        panelTranslucido1.setColorPrimario(new java.awt.Color(0, 255, 255));
        panelTranslucido1.setColorSecundario(new java.awt.Color(102, 102, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\m3l4n\\OneDrive\\Documentos\\NetBeansProjects\\PLANEA\\Images\\Logo PLANEA V2.png")); // NOI18N

        buttonAqua2.setBackground(new java.awt.Color(153, 153, 255));
        buttonAqua2.setForeground(new java.awt.Color(102, 102, 255));
        buttonAqua2.setText("Continuar Plan");
        buttonAqua2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonAqua3.setBackground(new java.awt.Color(153, 153, 255));
        buttonAqua3.setForeground(new java.awt.Color(102, 102, 255));
        buttonAqua3.setText("Administrar Planes");
        buttonAqua3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAqua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua3ActionPerformed(evt);
            }
        });

        buttonAqua4.setBackground(new java.awt.Color(153, 153, 255));
        buttonAqua4.setForeground(new java.awt.Color(102, 102, 255));
        buttonAqua4.setText("Nuevo Plan");
        buttonAqua4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAqua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua4ActionPerformed(evt);
            }
        });

        buttonTransluceIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\m3l4n\\OneDrive\\Documentos\\NetBeansProjects\\PLANEA\\Images\\home2.png")); // NOI18N
        buttonTransluceIcon1.setText("buttonTransluceIcon1");
        buttonTransluceIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransluceIcon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAqua3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAqua2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAqua4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonTransluceIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTransluceIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonAqua4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAqua2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAqua3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        add(panelTranslucido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTransluceIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransluceIcon2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonTransluceIcon2ActionPerformed

    private void buttonTransluceIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransluceIcon1ActionPerformed
                     
    }//GEN-LAST:event_buttonTransluceIcon1ActionPerformed

    private void buttonAqua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAqua3ActionPerformed

    private void buttonAqua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua4ActionPerformed
        Panel_tomaDatos panel1 = new Panel_tomaDatos(contenedorPrincipal);
        
         panel1.setBounds(0, 0, 800, 567);
        panel1.setVisible(true);      
            this.removeAll();
            contenedorPrincipal.setContentPane(panel1);
            this.revalidate();
            this.repaint();
    }//GEN-LAST:event_buttonAqua4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAqua buttonAqua2;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua3;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua4;
    private org.edisoncor.gui.button.ButtonTransluceIcon buttonTransluceIcon1;
    private org.edisoncor.gui.button.ButtonTransluceIcon buttonTransluceIcon2;
    private javax.swing.JLabel jLabel2;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido2;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(Image image) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
